Elcodi\MenuBundle\Entity\Menu\Node:
    type: entity
    repositoryClass: Elcodi\MenuBundle\Repository\NodeRepository
    table: menu_node
    fields:
        name:
            column: name
            type: string
            length: 255
            nullable: false
        url:
            column: url
            type: string
            length: 255
            nullable: true
        enabled:
            column: enabled
            type: boolean
            nullable: false
        createdAt:
            column: created_at
            type: datetime
        updatedAt:
            column: updated_at
            type: datetime

    manyToMany:
        subnodes:
            targetEntity: Elcodi\MenuBundle\Entity\Menu\Interfaces\NodeInterface
            cascade: [ "persist" ]
            joinTable:
                name: node_hierachy
                joinColumns:
                    menu_node_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    menu_subnode_id:
                        referencedColumnName: id

    lifecycleCallbacks:
        preUpdate: [loadUpdateAt]
        prePersist: [loadUpdateAt]
