parameters:

    #
    # Factories
    #
    elcodi.factory.menu_node.class: Elcodi\Component\Menu\Factory\NodeFactory
    elcodi.factory.menu.class: Elcodi\Component\Menu\Factory\MenuFactory

    #
    # Services
    #
    elcodi.manager.menu.class: Elcodi\Component\Menu\Services\MenuManager

    #
    # Twig extensions
    #
    elcodi.twig_extension.menu_print_route.class: Elcodi\Component\Menu\Twig\PrintRouteExtension
