parameters:

    #
    # Factories
    #
    elcodi.core.menu.factory.menu_node.class: Elcodi\Component\Menu\Factory\NodeFactory
    elcodi.core.menu.factory.menu.class: Elcodi\Component\Menu\Factory\MenuFactory

    #
    # Services
    #
    elcodi.core.menu.service.menu_manager.class: Elcodi\Component\Menu\Services\MenuManager

    #
    # Twig extensions
    #
    elcodi.core.menu.twig_extension.print_route.class: Elcodi\Component\Menu\Twig\PrintRouteExtension
