services:

    #
    # Factories
    #

    #
    # Factory for entity node
    #
    elcodi.factory.menu_node:
        class: %elcodi.factory.menu_node.class%
        calls:
            - [setEntityNamespace, ["%elcodi.core.menu.entity.menu_node.class%"]]

    #
    # Factory for entity menu
    #
    elcodi.factory.menu:
        class: %elcodi.factory.menu.class%
        calls:
            - [setEntityNamespace, ["%elcodi.core.menu.entity.menu.class%"]]
