services:

    #
    # Factories
    #

    #
    # Factory for entity node
    #
    elcodi.core.menu.factory.menu_node:
        class: %elcodi.core.menu.factory.menu_node.class%
        calls:
            - [setEntityNamespace, ["%elcodi.core.menu.entity.menu_node.class%"]]

    elcodi.factory.menu_node:
        alias: elcodi.core.menu.factory.menu_node

    #
    # Factory for entity menu
    #
    elcodi.core.menu.factory.menu:
        class: %elcodi.core.menu.factory.menu.class%
        calls:
            - [setEntityNamespace, ["%elcodi.core.menu.entity.menu.class%"]]

    elcodi.factory.menu:
        alias: elcodi.core.menu.factory.menu

    #
    # Entity providers
    #

    #
    # Instance provider for entity node
    #
    elcodi.core.menu.entity.menu_node.instance:
        class: %elcodi.core.menu.entity.menu_node.class%
        factory_service: elcodi.core.menu.factory.menu_node
        factory_method: create
        scope: prototype

    elcodi.entity.menu_node.instance:
        alias: elcodi.core.menu.entity.menu_node.instance

    #
    # Instance provider for entity menu
    #
    elcodi.core.menu.entity.menu.instance:
        class: %elcodi.core.menu.entity.menu.class%
        factory_service: elcodi.core.menu.factory.menu
        factory_method: create
        scope: prototype

    elcodi.entity.menu.instance:
        alias: elcodi.core.menu.entity.menu.instance
