services:

    #
    # Menu filters
    #
    elcodi.menu_filter.menu_disabled:
        class: Elcodi\Component\Menu\Filter\MenuDisabledFilter
        tags:
            - { name: menu.filter }

    #
    # Menu modifiers
    #
    elcodi.menu_modifier.menu_active:
        class: Elcodi\Component\Menu\Modifier\MenuActiveModifier
        arguments:
            - @request_stack
        tags:
            - { name: menu.modifier }

    elcodi.menu_modifier.menu_expanded:
        class: Elcodi\Component\Menu\Modifier\MenuExpandedModifier
        arguments:
            - @request_stack
        tags:
            - { name: menu.modifier }
