services:

    #
    # Repositories
    #
    # Repository for entity node
    #
    elcodi.repository.menu_node:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: elcodi.repository_provider
        factory_method: getRepositoryByEntityNamespace
        arguments:
            entity_namespace: %elcodi.core.menu.entity.menu_node.class%

    #
    # Repository for entity menu
    #
    elcodi.repository.menu:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: elcodi.repository_provider
        factory_method: getRepositoryByEntityNamespace
        arguments:
            entity_namespace: %elcodi.core.menu.entity.menu.class%
