services:

    #
    # services
    #
    elcodi.manager.menu:
        class: %elcodi.manager.menu.class%
        arguments:
            - @elcodi.repository.menu
            - %elcodi.core.menu.cache_key%
        calls:
            - [setCache, [@doctrine_cache.providers.elcodi_menus]]
            - [setEncoder, [@elcodi.json_encoder]]
