services:

    #
    # services
    #
    elcodi.manager.menu:
        class: Elcodi\Component\Menu\Services\MenuManager
        arguments:
            - @elcodi.event_dispatcher.menu
            - @elcodi.processor.menu_event
            - @elcodi.serializer.menu
            - @elcodi.repository.menu
            - %elcodi.core.menu.cache_key%
        calls:
            - [setCache, [@doctrine_cache.providers.elcodi_menus]]
            - [setEncoder, [@elcodi.json_encoder]]

    elcodi.serializer.menu:
        class: Elcodi\Component\Menu\Serializer\MenuArraySerializer
        public: false

    elcodi.processor.menu_event:
        class: Elcodi\Component\Menu\Processor\MenuEventProcessor
        arguments:
            - @elcodi.serializer.menu
