services:

    #
    # Twig extensions
    #
    elcodi.core.menu.twig_extension.print_route:
        class: %elcodi.core.menu.twig_extension.print_route.class%
        arguments:
            router: @router
        tags:
            - { name: twig.extension }
