parameters:

    #
    # DummyRouter Adapter class
    #
    elcodi.adapter.menu_route_generator.dummy.class: Elcodi\Component\Menu\Adapter\RouteGenerator\DummyRouteGeneratorAdapter

services:

    #
    # DummyRouter Adapter
    #
    elcodi.adapter.menu_route_generator.dummy:
        class: %elcodi.adapter.menu_route_generator.dummy.class%

    elcodi.adapter.menu_route_generator:
        alias: elcodi.adapter.menu_route_generator.dummy
