parameters:

    #
    # SymfonyRouter Adapter class
    #
    elcodi.adapter.menu_route_generator.symfony_routing.class: Elcodi\Component\Menu\Adapter\RouteGenerator\SymfonyRouteGeneratorAdapter

services:

    #
    # SymfonyRouter Adapter
    #
    elcodi.adapter.menu_route_generator.symfony_routing:
        class: %elcodi.adapter.menu_route_generator.symfony_routing.class%
        arguments:
            - @router

    elcodi.adapter.menu_route_generator:
        alias: elcodi.adapter.menu_route_generator.symfony_routing
